/* soapAdvancedSecurityServiceBindingService.h
   Generated by gSOAP 2.8.122 for server/onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapAdvancedSecurityServiceBindingService_H
#define soapAdvancedSecurityServiceBindingService_H
#include "soapH.h"

    class SOAP_CMAC AdvancedSecurityServiceBindingService {
      public:
        /// Context to manage service IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this service and should be deleted by the destructor
        bool soap_own;
        /// Variables globally declared in server/onvif.h, if any
        /// Construct a service with new managing context
        AdvancedSecurityServiceBindingService();
        /// Copy constructor
        AdvancedSecurityServiceBindingService(const AdvancedSecurityServiceBindingService&);
        /// Construct service given a shared managing context
        AdvancedSecurityServiceBindingService(struct soap*);
        /// Constructor taking input+output mode flags for the new managing context
        AdvancedSecurityServiceBindingService(soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        AdvancedSecurityServiceBindingService(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the constructor
        virtual ~AdvancedSecurityServiceBindingService();
        /// Delete all deserialized data (with soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to defaults
        virtual void reset();
        /// Initializer used by constructors
        virtual void AdvancedSecurityServiceBindingService_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual AdvancedSecurityServiceBindingService *copy() SOAP_PURE_VIRTUAL_COPY;
        /// Copy assignment
        AdvancedSecurityServiceBindingService& operator=(const AdvancedSecurityServiceBindingService&);
        /// Close connection (normally automatic)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Return sender-related fault to sender
        virtual int soap_senderfault(const char *string, const char *detailXML);
        /// Return sender-related fault with SOAP 1.2 subcode to sender
        virtual int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
        /// Return receiver-related fault to sender
        virtual int soap_receiverfault(const char *string, const char *detailXML);
        /// Return receiver-related fault with SOAP 1.2 subcode to sender
        virtual int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance, struct wsdd__AppSequenceType *wsdd__AppSequence, struct _wsse__Security *wsse__Security);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
    #ifndef WITH_NOIO
        /// Run simple single-thread (iterative, non-SSL) service on port until a connection error occurs (returns SOAP_OK or error code), use this->bind_flag = SO_REUSEADDR to rebind for immediate rerun
        virtual int run(int port, int backlog = 1);
    #if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
        /// Run simple single-thread SSL service on port until a connection error occurs (returns SOAP_OK or error code), use this->bind_flag = SO_REUSEADDR to rebind for immediate rerun
        virtual int ssl_run(int port, int backlog = 1);
    #endif
        /// Bind service to port (returns master socket or SOAP_INVALID_SOCKET upon error)
        virtual SOAP_SOCKET bind(const char *host, int port, int backlog);
        /// Accept next request (returns socket or SOAP_INVALID_SOCKET upon error)
        virtual SOAP_SOCKET accept();
    #if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
        /// When SSL is used, after accept() should perform and accept SSL handshake
        virtual int ssl_accept();
    #endif
    #endif
        /// After accept() serve the pending request (returns SOAP_OK or error code)
        virtual int serve();
        /// Used by serve() to dispatch a pending request (returns SOAP_OK or error code)
        virtual int dispatch();
        virtual int dispatch(struct soap *soap);
        //
        // Service operations are listed below: you should define these
        // Note: compile with -DWITH_PURE_VIRTUAL to declare pure virtual methods
        //
        /// Web service operation 'GetServiceCapabilities' implementation, should return SOAP_OK or error code
        virtual int GetServiceCapabilities(_tas__GetServiceCapabilities *tas__GetServiceCapabilities, _tas__GetServiceCapabilitiesResponse &tas__GetServiceCapabilitiesResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'CreateRSAKeyPair' implementation, should return SOAP_OK or error code
        virtual int CreateRSAKeyPair(_tas__CreateRSAKeyPair *tas__CreateRSAKeyPair, _tas__CreateRSAKeyPairResponse &tas__CreateRSAKeyPairResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'UploadKeyPairInPKCS8' implementation, should return SOAP_OK or error code
        virtual int UploadKeyPairInPKCS8(_tas__UploadKeyPairInPKCS8 *tas__UploadKeyPairInPKCS8, _tas__UploadKeyPairInPKCS8Response &tas__UploadKeyPairInPKCS8Response) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'UploadCertificateWithPrivateKeyInPKCS12' implementation, should return SOAP_OK or error code
        virtual int UploadCertificateWithPrivateKeyInPKCS12(_tas__UploadCertificateWithPrivateKeyInPKCS12 *tas__UploadCertificateWithPrivateKeyInPKCS12, _tas__UploadCertificateWithPrivateKeyInPKCS12Response &tas__UploadCertificateWithPrivateKeyInPKCS12Response) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetKeyStatus' implementation, should return SOAP_OK or error code
        virtual int GetKeyStatus(_tas__GetKeyStatus *tas__GetKeyStatus, _tas__GetKeyStatusResponse &tas__GetKeyStatusResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetPrivateKeyStatus' implementation, should return SOAP_OK or error code
        virtual int GetPrivateKeyStatus(_tas__GetPrivateKeyStatus *tas__GetPrivateKeyStatus, _tas__GetPrivateKeyStatusResponse &tas__GetPrivateKeyStatusResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetAllKeys' implementation, should return SOAP_OK or error code
        virtual int GetAllKeys(_tas__GetAllKeys *tas__GetAllKeys, _tas__GetAllKeysResponse &tas__GetAllKeysResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'DeleteKey' implementation, should return SOAP_OK or error code
        virtual int DeleteKey(_tas__DeleteKey *tas__DeleteKey, _tas__DeleteKeyResponse &tas__DeleteKeyResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'CreatePKCS10CSR' implementation, should return SOAP_OK or error code
        virtual int CreatePKCS10CSR(_tas__CreatePKCS10CSR *tas__CreatePKCS10CSR, _tas__CreatePKCS10CSRResponse &tas__CreatePKCS10CSRResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'CreateSelfSignedCertificate' implementation, should return SOAP_OK or error code
        virtual int CreateSelfSignedCertificate(_tas__CreateSelfSignedCertificate *tas__CreateSelfSignedCertificate, _tas__CreateSelfSignedCertificateResponse &tas__CreateSelfSignedCertificateResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'UploadCertificate' implementation, should return SOAP_OK or error code
        virtual int UploadCertificate(_tas__UploadCertificate *tas__UploadCertificate, _tas__UploadCertificateResponse &tas__UploadCertificateResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetCertificate' implementation, should return SOAP_OK or error code
        virtual int GetCertificate(_tas__GetCertificate *tas__GetCertificate, _tas__GetCertificateResponse &tas__GetCertificateResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetAllCertificates' implementation, should return SOAP_OK or error code
        virtual int GetAllCertificates(_tas__GetAllCertificates *tas__GetAllCertificates, _tas__GetAllCertificatesResponse &tas__GetAllCertificatesResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'DeleteCertificate' implementation, should return SOAP_OK or error code
        virtual int DeleteCertificate(_tas__DeleteCertificate *tas__DeleteCertificate, _tas__DeleteCertificateResponse &tas__DeleteCertificateResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'CreateCertificationPath' implementation, should return SOAP_OK or error code
        virtual int CreateCertificationPath(_tas__CreateCertificationPath *tas__CreateCertificationPath, _tas__CreateCertificationPathResponse &tas__CreateCertificationPathResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetCertificationPath' implementation, should return SOAP_OK or error code
        virtual int GetCertificationPath(_tas__GetCertificationPath *tas__GetCertificationPath, _tas__GetCertificationPathResponse &tas__GetCertificationPathResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetAllCertificationPaths' implementation, should return SOAP_OK or error code
        virtual int GetAllCertificationPaths(_tas__GetAllCertificationPaths *tas__GetAllCertificationPaths, _tas__GetAllCertificationPathsResponse &tas__GetAllCertificationPathsResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'DeleteCertificationPath' implementation, should return SOAP_OK or error code
        virtual int DeleteCertificationPath(_tas__DeleteCertificationPath *tas__DeleteCertificationPath, _tas__DeleteCertificationPathResponse &tas__DeleteCertificationPathResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'UploadPassphrase' implementation, should return SOAP_OK or error code
        virtual int UploadPassphrase(_tas__UploadPassphrase *tas__UploadPassphrase, _tas__UploadPassphraseResponse &tas__UploadPassphraseResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetAllPassphrases' implementation, should return SOAP_OK or error code
        virtual int GetAllPassphrases(_tas__GetAllPassphrases *tas__GetAllPassphrases, _tas__GetAllPassphrasesResponse &tas__GetAllPassphrasesResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'DeletePassphrase' implementation, should return SOAP_OK or error code
        virtual int DeletePassphrase(_tas__DeletePassphrase *tas__DeletePassphrase, _tas__DeletePassphraseResponse &tas__DeletePassphraseResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'UploadCRL' implementation, should return SOAP_OK or error code
        virtual int UploadCRL(_tas__UploadCRL *tas__UploadCRL, _tas__UploadCRLResponse &tas__UploadCRLResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetCRL' implementation, should return SOAP_OK or error code
        virtual int GetCRL(_tas__GetCRL *tas__GetCRL, _tas__GetCRLResponse &tas__GetCRLResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetAllCRLs' implementation, should return SOAP_OK or error code
        virtual int GetAllCRLs(_tas__GetAllCRLs *tas__GetAllCRLs, _tas__GetAllCRLsResponse &tas__GetAllCRLsResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'DeleteCRL' implementation, should return SOAP_OK or error code
        virtual int DeleteCRL(_tas__DeleteCRL *tas__DeleteCRL, _tas__DeleteCRLResponse &tas__DeleteCRLResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'CreateCertPathValidationPolicy' implementation, should return SOAP_OK or error code
        virtual int CreateCertPathValidationPolicy(_tas__CreateCertPathValidationPolicy *tas__CreateCertPathValidationPolicy, _tas__CreateCertPathValidationPolicyResponse &tas__CreateCertPathValidationPolicyResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetCertPathValidationPolicy' implementation, should return SOAP_OK or error code
        virtual int GetCertPathValidationPolicy(_tas__GetCertPathValidationPolicy *tas__GetCertPathValidationPolicy, _tas__GetCertPathValidationPolicyResponse &tas__GetCertPathValidationPolicyResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetAllCertPathValidationPolicies' implementation, should return SOAP_OK or error code
        virtual int GetAllCertPathValidationPolicies(_tas__GetAllCertPathValidationPolicies *tas__GetAllCertPathValidationPolicies, _tas__GetAllCertPathValidationPoliciesResponse &tas__GetAllCertPathValidationPoliciesResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'DeleteCertPathValidationPolicy' implementation, should return SOAP_OK or error code
        virtual int DeleteCertPathValidationPolicy(_tas__DeleteCertPathValidationPolicy *tas__DeleteCertPathValidationPolicy, _tas__DeleteCertPathValidationPolicyResponse &tas__DeleteCertPathValidationPolicyResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'AddServerCertificateAssignment' implementation, should return SOAP_OK or error code
        virtual int AddServerCertificateAssignment(_tas__AddServerCertificateAssignment *tas__AddServerCertificateAssignment, _tas__AddServerCertificateAssignmentResponse &tas__AddServerCertificateAssignmentResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'RemoveServerCertificateAssignment' implementation, should return SOAP_OK or error code
        virtual int RemoveServerCertificateAssignment(_tas__RemoveServerCertificateAssignment *tas__RemoveServerCertificateAssignment, _tas__RemoveServerCertificateAssignmentResponse &tas__RemoveServerCertificateAssignmentResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'ReplaceServerCertificateAssignment' implementation, should return SOAP_OK or error code
        virtual int ReplaceServerCertificateAssignment(_tas__ReplaceServerCertificateAssignment *tas__ReplaceServerCertificateAssignment, _tas__ReplaceServerCertificateAssignmentResponse &tas__ReplaceServerCertificateAssignmentResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetAssignedServerCertificates' implementation, should return SOAP_OK or error code
        virtual int GetAssignedServerCertificates(_tas__GetAssignedServerCertificates *tas__GetAssignedServerCertificates, _tas__GetAssignedServerCertificatesResponse &tas__GetAssignedServerCertificatesResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'SetEnabledTLSVersions' implementation, should return SOAP_OK or error code
        virtual int SetEnabledTLSVersions(_tas__SetEnabledTLSVersions *tas__SetEnabledTLSVersions, _tas__SetEnabledTLSVersionsResponse &tas__SetEnabledTLSVersionsResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetEnabledTLSVersions' implementation, should return SOAP_OK or error code
        virtual int GetEnabledTLSVersions(_tas__GetEnabledTLSVersions *tas__GetEnabledTLSVersions, _tas__GetEnabledTLSVersionsResponse &tas__GetEnabledTLSVersionsResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'SetClientAuthenticationRequired' implementation, should return SOAP_OK or error code
        virtual int SetClientAuthenticationRequired(_tas__SetClientAuthenticationRequired *tas__SetClientAuthenticationRequired, _tas__SetClientAuthenticationRequiredResponse &tas__SetClientAuthenticationRequiredResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetClientAuthenticationRequired' implementation, should return SOAP_OK or error code
        virtual int GetClientAuthenticationRequired(_tas__GetClientAuthenticationRequired *tas__GetClientAuthenticationRequired, _tas__GetClientAuthenticationRequiredResponse &tas__GetClientAuthenticationRequiredResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'SetCnMapsToUser' implementation, should return SOAP_OK or error code
        virtual int SetCnMapsToUser(_tas__SetCnMapsToUser *tas__SetCnMapsToUser, _tas__SetCnMapsToUserResponse &tas__SetCnMapsToUserResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetCnMapsToUser' implementation, should return SOAP_OK or error code
        virtual int GetCnMapsToUser(_tas__GetCnMapsToUser *tas__GetCnMapsToUser, _tas__GetCnMapsToUserResponse &tas__GetCnMapsToUserResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'AddCertPathValidationPolicyAssignment' implementation, should return SOAP_OK or error code
        virtual int AddCertPathValidationPolicyAssignment(_tas__AddCertPathValidationPolicyAssignment *tas__AddCertPathValidationPolicyAssignment, _tas__AddCertPathValidationPolicyAssignmentResponse &tas__AddCertPathValidationPolicyAssignmentResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'RemoveCertPathValidationPolicyAssignment' implementation, should return SOAP_OK or error code
        virtual int RemoveCertPathValidationPolicyAssignment(_tas__RemoveCertPathValidationPolicyAssignment *tas__RemoveCertPathValidationPolicyAssignment, _tas__RemoveCertPathValidationPolicyAssignmentResponse &tas__RemoveCertPathValidationPolicyAssignmentResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'ReplaceCertPathValidationPolicyAssignment' implementation, should return SOAP_OK or error code
        virtual int ReplaceCertPathValidationPolicyAssignment(_tas__ReplaceCertPathValidationPolicyAssignment *tas__ReplaceCertPathValidationPolicyAssignment, _tas__ReplaceCertPathValidationPolicyAssignmentResponse &tas__ReplaceCertPathValidationPolicyAssignmentResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetAssignedCertPathValidationPolicies' implementation, should return SOAP_OK or error code
        virtual int GetAssignedCertPathValidationPolicies(_tas__GetAssignedCertPathValidationPolicies *tas__GetAssignedCertPathValidationPolicies, _tas__GetAssignedCertPathValidationPoliciesResponse &tas__GetAssignedCertPathValidationPoliciesResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'AddDot1XConfiguration' implementation, should return SOAP_OK or error code
        virtual int AddDot1XConfiguration(_tas__AddDot1XConfiguration *tas__AddDot1XConfiguration, _tas__AddDot1XConfigurationResponse &tas__AddDot1XConfigurationResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetAllDot1XConfigurations' implementation, should return SOAP_OK or error code
        virtual int GetAllDot1XConfigurations(_tas__GetAllDot1XConfigurations *tas__GetAllDot1XConfigurations, _tas__GetAllDot1XConfigurationsResponse &tas__GetAllDot1XConfigurationsResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetDot1XConfiguration' implementation, should return SOAP_OK or error code
        virtual int GetDot1XConfiguration(_tas__GetDot1XConfiguration *tas__GetDot1XConfiguration, _tas__GetDot1XConfigurationResponse &tas__GetDot1XConfigurationResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'DeleteDot1XConfiguration' implementation, should return SOAP_OK or error code
        virtual int DeleteDot1XConfiguration(_tas__DeleteDot1XConfiguration *tas__DeleteDot1XConfiguration, _tas__DeleteDot1XConfigurationResponse &tas__DeleteDot1XConfigurationResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'SetNetworkInterfaceDot1XConfiguration' implementation, should return SOAP_OK or error code
        virtual int SetNetworkInterfaceDot1XConfiguration(_tas__SetNetworkInterfaceDot1XConfiguration *tas__SetNetworkInterfaceDot1XConfiguration, _tas__SetNetworkInterfaceDot1XConfigurationResponse &tas__SetNetworkInterfaceDot1XConfigurationResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'GetNetworkInterfaceDot1XConfiguration' implementation, should return SOAP_OK or error code
        virtual int GetNetworkInterfaceDot1XConfiguration(_tas__GetNetworkInterfaceDot1XConfiguration *tas__GetNetworkInterfaceDot1XConfiguration, _tas__GetNetworkInterfaceDot1XConfigurationResponse &tas__GetNetworkInterfaceDot1XConfigurationResponse) SOAP_PURE_VIRTUAL;
        //
        /// Web service operation 'DeleteNetworkInterfaceDot1XConfiguration' implementation, should return SOAP_OK or error code
        virtual int DeleteNetworkInterfaceDot1XConfiguration(_tas__DeleteNetworkInterfaceDot1XConfiguration *tas__DeleteNetworkInterfaceDot1XConfiguration, _tas__DeleteNetworkInterfaceDot1XConfigurationResponse &tas__DeleteNetworkInterfaceDot1XConfigurationResponse) SOAP_PURE_VIRTUAL;
    };
#endif
